# Generated by Django 5.0 on 2023-12-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_profile_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('price', models.ImageField(upload_to='')),
                ('rating', models.FloatField()),
                ('image', models.ImageField(upload_to='productImages')),
            ],
        ),
    ]
