# Generated by Django 5.0 on 2023-12-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_products_price_cart_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id_user',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='productImages/'),
        ),
    ]
