# Generated by Django 5.0 on 2023-12-28 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_cart_id_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default=None, max_length=17),
        ),
        migrations.AddField(
            model_name='orders',
            name='rating',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
