# Generated by Django 5.0 on 2023-12-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_orders_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='users',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
